services:
  mysql:
    image: mysql:8
    container_name: mgmt-system-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1561
      MYSQL_DATABASE: mgmt_system_db
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1561"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mgmt-system:v1.2
    build: .
    container_name: mgmt-system
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mgmt_system_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1561
    ports:
      - "8080:8080"

volumes:
  mysql-data: